apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/jx-cb-gke/stu-golang:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/jx-cb-gke/stu-golang:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: stu-golang
        chartPath: charts/stu-golang
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/jx-cb-gke/stu-golang'
          image.tag: '{{.DIGEST_HEX}}'
